version: "3.1"

volumes:
  db:

services:
  db:
    image: postgres
    # Uncomment to log all queries
    command: ["postgres", "-c", "log_statement=all"]
    restart: always
    environment:
      # postgresql://user:pass@localhost:5432/webstudio
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: webstudio
      POSTGRES_USER: user
    volumes:
      - db:/var/lib/postgresql
    ports:
      - ${PGPORT:-5433}:5432

  postgrest:
    image: postgrest/postgrest
    restart: always
    environment:
      PGRST_JWT_SECRET: "56b850d1ed42a5bb10a73f31863bb8f024121eb99f0c9675be267b04d4d7abe9"
      PGRST_DB_URI: postgres://user:pass@localhost:5433/webstudio
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: user
      PGRST_SERVER_PORT: 3000
    ports:
      - 3000:3000
